### ISSUE TITLE
EC2 instance

### ISSUE THREAD

**Issue by gabriben** [bstatcomp/stan_gpu_install_docs#1]
It might be too soon for such a question but have you made this work on an AWS EC2 instance? 
If yes, how?

Thank you in advance

**Comment by rok-cesnovar** [comment]
Sorry, we missed this issue. The minimum instructions for AWS EC2 instances are:

```
sudo apt-get -y update
sudo apt-get install -y nvidia-driver-460 nvidia-cuda-toolkit clinfo
```

Someone seeing this at a later point should replaced `460` with a larger number if available.

**Comment by rok-cesnovar** [comment]
The instructions have been updated to also include the driver installation: https://github.com/bstatcomp/stan_gpu_install_docs/blob/master/install_docs/INSTALL_CMDSTAN.md

Will close this.
